language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - release
cache:
  directories:
  - "$HOME/.m2"
notifications:
  slack:
    secure: X/nkGp8Jsy87YNA/D2T2L/pC13pM8ywoZKL9JZFOgSnpqpymNBNXGX7w4aJ83srrdC9DSy+HGkcXxhBjmrhtnn3nuBgGz0brtzhH0Ly6l2CEjvVSqSRrjHZ6IC+frbOYfaNuSwdmMPIeADBNDqZ7EIdE/RE+iB1qD7hFyKC5KADCrzuyaksMXTsKFiBJfgYaRq1SpW5CBY7v66YeyHSYKJpMplLRCgqv9jn2mAW4rp90bDpsOoaa/6UA9qxwSD4bZslln0TvLal8wd+0NnSlxwqW6bekNMNZ5N1HwkRvA7kUjEZ/pYgqBGF1vKOUXFpDBxqXA6aRxbOZtHGS7DjLNVi+EO7qdK+XUhGiKRnpnskaKmYWM7+NaoN4A2cfo4ifps7x0ZkESSvmeOnWDs0SEqCAtVli/EqpoiJzajI60/dDQ7Ax2De7rGlgfWTDeiKJ+VX0cgjaaZGZOCkSgz1vaWoJSFaaLrnwJ6EkdHHnpkPJR4h1QzdrWWPgdAyMmuMg/Y+bb0oWM2mfnN/6xkzH6QrfEnXOYEsVveNXd2wY/WjI61hBL6K+FnwZnKg+iO5JmNHaHuj/CucDhiX66KnL7RHDrmXLwUmPdI/7jm2cYVXjlsMx13UccIxH+JzQSa/uiguWoSXtUsPQlizKMzsHCjHK6Lu/LcFFWYSWcGAKxNA=
    on_success: change
    on_failure: always