language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - release
cache:
  directories:
  - $HOME/.m2
notifications:
  slack:
    secure: ZaL5XJaZkiVSpcPTrce6AM6xX1tBEB7n8Z1nETGZBbP4b4kr73jnOMIkaQ4gMy9+iCnBuYW+z7+omqr2IfJgu5ukGgaS8TvEDexaFCtMwJDARpB8wR9e2O6SzTK+9XPukfAO4w4rxMfijzok2UAfagsJUe9OC+RjEXDdn5790TdL5luiH1Y6wo0LxDrrJmBCcVoPoa9ftfIJ/e2wZZX1QwtVZorUEp8Rr9Q4cAE/1mkfg+L79EeKe5PZYLyj3YjMWpNuguoFS3x2wx9Olr6oOHXd00BZYSEuN0EP3L/Ft/d2Qc8rBBOCID+vHITAmdofAwTWz4O5Kd9NcvzPFJPQdAtAFw9jooPuNLC1grAxriCZA4bP5TxL9z/g/qodR/R98ODq35u9przpM2OTvR7fPJ7nm1AIB6YFpRu2Ek0s5HI6Xwajfz8jjhRkLN3ofpVMKmFkVCShHTbIWETJ2X+dsW0D719f4+gX/Avza8n8M+c7Y9mgccJsfdrtHYXK2gDQiBOLNfZJkHc2tt5o2HI1gyHkJz8dhCrxg+jR129OifD6mPc3j6yEQSWWscDlB8AePotNhcxAtTVWd0VxZJavBo6biU2u7ZkpWURgH4FR2f3iXXnuyMjkNwz9OVCXoJYDqzDxJzCFt7JKCFK9fbooWH22jevzEkXZ4q/p82cYG2c=
