language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - release
cache:
  directories:
  - $HOME/.m2
notifications:
  slack:
    secure: aFXkt2incNK63f4wYVCcmwpWW+q1ZQ/jKC6nKn4uZjVn7MHRDka5dHwgqFnDdUQoUPjZF7rpBBlrDH3J63h1VksU1qOIsP7f/qWJX4uBIRmixyHxJ/9Jqeky8DhdCQjFAuNbeIDjQvi811nlV+YoIZnQJ7277lYgJnNg7MrvWXDNqB/llubqNip9VYCg4pqe+iKBPb3sd2YSSJqm9zkU3Ih9f7k3b5+GxdGYKimOKpmZkYDVXwPjhSpx4q6YqM0a0C1nSLdZZkK2Vk0FKtJphcPdszZefJGcK3UrSmp06cHfohNlkpaZo7nrMGBfJ0Jpw8RTJlhYO1VFjPwLgUblZWD9PrrVi0MfcU4uhpcrfGZbfM2AMurcDysvQ0/vAnnoN+aDK0GmwN+AtSTuglhDsnqrpSeYqDgb6t0K8C6YqIk2KSxZGMDIbQBtNiz8xJwUdfqvp14BGJyN9/i8K+knbOx6YWUwztXO2cL+A5f3g37uUyfscaNQ3b11fQuRiTpgUu+Uyx16422LBJheW9dI7714ofpBQ5ap+o6bdOpn4TNnWFeqyH/Tud7iRqSE+ut6KTuC3SAJB7Guo4rYroZird+vI9U9kQzKPStsEhdIci0AttZWPJcVWVwzgreRh627j2r2beDwUBdRULwYgujDvAt/WhaO9RFiLr22Zmem7n0=
